baseURL = 'https://zl3clv.nz/'
languageCode = 'en-us'
title = 'ZL3CLV'
theme = ["anatole", "easy-gallery"]
publishDir = "docs"
enableRobotsTXT = true


[params]
title = "ZL3CLV | David Palmer"
author = "David Palmer"
description = ""
profilePicture = "images/zl3clv.svg"
customCss = ["css/custom.css"]
reversepagetitle = true

    [[params.socialIcons]]
    icon = "fab fa-youtube"
    title = "Youtube"
    url = "https://www.youtube.com/channel/UC_t4tH-Owb-nOXay9oD4isA"

    [[params.socialIcons]]
    icon = "fas fa-running"
    title = "cloventt.net"
    url = "https://cloventt.net"

    [params.plausibleAnalytics]
    domain = "example.com"